preferences:
  general:
    audioLib: sounddevice
    units: deg

study:
  no_exps: 2
  exp2:
    SOAs: [-100, -30, 0, 30, 100]
    num_reps: 3
    num_blocks: 8
    practice_trials: 20

stimuli:
  num_singletons: 2
  bg_orientation: [10, -10]
  singleton_orientation: [30, -30]
  x_count: 21
  y_count: 21
  spacing: 0.7 # spacing between elements
  line_length: 0.7
  line_width: 0.1
  line_color: "#AAAAAA"
  fix_check_rad: 1.5  # How far away from fixation before trial restart
  singleton_area: 2.4  # How close to singleton before successful saccade counted

trial_info:
  initialization_time: 200
  ITI: 800
  max_response_time: 2000
  ITI_wait: 100  # Keep items on screen so doesn't feel to rushed
  jitter: 100  # Random jitter between -<jitter>, +<jitter>

window: # refers to the parameters for the Psychopy Window class
  units: pix
  color: [0, 0, 0] # psychopy rgb
  fullscr: True
  screen: 0 #0 #1
  winType: 'pyglet'
  waitBlanking: True
  colorSpace: 'rgb' #'hsv' #'rgb255'

monitor:
  name: default
  width: 52.6 # width of monitor (in cm)
  distance: 73 # distance of participant from monitor (in cm)
  gamma: 1 # specific value for gamma correction

monitor_extra:
  height: 30 # height of monitor (in cm)

mouse:
  visible: False

window_extra: # refers to the parameters for the OLD Psychopy Window class (new version breaks)
  size: [1920, 1080] #[1680, 1050]
  pos: [0, 0]
  framerate: 60
  mac_bool: False #True #False

paths:
  curr_dir:  'local'
  data_pth: {'lab': 'C:\Users\crowding_search_2\DATA\', 'srvr': '\\labssrv\crowding_search_2\DATA'}

eyetracker:
  address: '100.1.1.1' #  Eyelink eyetracker IP
  dot_size: 0.15  # in dva
  options: # Eyelink specific settings
    calibration_type: HV9  # [H3, HV3, HV5, HV9]
    sample_rate: 1000
    calibration_area_proportion: 0.7 0.7 #0.88 0.83
    validation_area_proportion: 0.7 0.7 #0.88 0.83
